# Generated by Django 2.2.9 on 2019-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
