# Generated by Django 2.2.9 on 2019-12-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='BoardModel',
        ),
    ]
