# Generated by Django 3.0.1 on 2019-12-21 19:43

from django.db import migrations
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chain_app', '0003_mymodelwithfigure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodelwithfigure',
            name='fig',
        ),
        migrations.AddField(
            model_name='mymodelwithfigure',
            name='figure',
            field=django_matplotlib.fields.MatplotlibFigureField(),
        ),
    ]
