# Generated by Django 3.0.1 on 2019-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_app', '0004_auto_20191221_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='bstate',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
