# Generated by Django 2.2.9 on 2019-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_app', '0005_boardmodel_bstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='loadFlag',
            field=models.BooleanField(default=False),
        ),
    ]
